CREATE TABLE IN_DEPT (
    EID INT NOT NULL,
    DID INT NOT NULL,
    Percent_Time INT NOT NULL DEFAULT 0,
    CONSTRAINT IN_DEPT_PRIM 
    PRIMARY KEY (EID, DID),
    CONSTRAINT FK_EMP_EID 
    FOREIGN KEY (EID) REFERENCES EMP(EID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    CONSTRAINT FK_DEPT_DID 
    FOREIGN KEY (DID) REFERENCES DEPT(DID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    CONSTRAINT POSITIVE_PERCENT_TIME CHECK (Percent_Time >= 0)
);


-- ==================================================
-- ==================================================


SELECT DEPT.DName
FROM DEPT 
LEFT OUTER JOIN IN_DEPT ON DEPT.DID = IN_DEPT.DID
WHERE IN_DEPT.EID IS NULL;


SELECT BUILDING.BName
FROM BUILDING 
JOIN IN_BUILDING ON BUILDING.BID = IN_BUILDING.BID
GROUP BY BUILDING.BName
HAVING COUNT(IN_BUILDING.EID) > 50;


SELECT DEPT.DName
FROM DEPT
JOIN IN_DEPT ON DEPT.DID = IN_DEPT.DID
JOIN DEPT ON IN_DEPT.DID = DEPT.DID
WHERE EMP.Salary = (
    SELECT MAX(SALARY)
    FROM EMP
);


UPDATE EMP
SET SALARY = SALARY + 10000
WHERE EID IN (
    SELECT MANAGES_DEPT.EID
    FROM MANAGES_DEPT
    JOIN IN_DEPT ON MANAGES_DEPT.DID = IN_DEPT.DID
    GROUP BY MANAGES_DEPT.EID
    HAVING COUNT(IN_DEPT.EID) > 50
);


DELETE FROM BUILDING
WHERE BID NOT IN (
    SELECT BID
    FROM IN_BUILDING
    GROUP BY BID
    HAVING COUNT(EID) > 50
);


CREATE ASSERTION MANAGE_CONSTRAINT
CHECK (
    NOT EXISTS (
        SELECT EID
        FROM MANAGES_DEPT
        GROUP BY EID
        HAVING COUNT(DID) > 3
    )
);


CREATE VIEW BUILDING
AS SELECT BUILDING.BName, COUNT(IN_BUILDING.EID)
FROM BUILDING
LEFT OUTER JOIN IN_BUILDING ON BUILDING.BID = IN_BUILDING.BID
GROUP BY BUILDING.BName;